//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservanto.CustomBooknow.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservanto.CustomBooknow.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte prosím termín..
        /// </summary>
        public static string AppointmentMustBeSelected {
            get {
                return ResourceManager.GetString("AppointmentMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervační údaje.
        /// </summary>
        public static string BookingDetails {
            get {
                return ResourceManager.GetString("BookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše rezervace byla dokončena!.
        /// </summary>
        public static string BookingFinished {
            get {
                return ResourceManager.GetString("BookingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte prosím požadovanou službu..
        /// </summary>
        public static string BookingResourceAndServiceMustBeSelected {
            get {
                return ResourceManager.GetString("BookingResourceAndServiceMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín.
        /// </summary>
        public static string BookingTime {
            get {
                return ResourceManager.GetString("BookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalendář.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte termín.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte požadovanou službu.
        /// </summary>
        public static string ChooseService {
            get {
                return ResourceManager.GetString("ChooseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00 Kč.
        /// </summary>
        public static string CurrencyFormat {
            get {
                return ResourceManager.GetString("CurrencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokončit.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výberte provozovnu.
        /// </summary>
        public static string LocationSelect {
            get {
                return ResourceManager.GetString("LocationSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další stránka.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonní číslo.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte, kam se chcete rezervovat.
        /// </summary>
        public static string SegmentSelect {
            get {
                return ResourceManager.GetString("SegmentSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online rezervace.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbývá uhradit.
        /// </summary>
        public static string ToBePaid {
            get {
                return ResourceManager.GetString("ToBePaid", resourceCulture);
            }
        }
    }
}
